---
title: "ProyectoTD2023"
author: "ProyectoTD Grupo B"
date: "2023-04-26"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

CARGA DE LIBRERIAS

```{r}
library(tidyverse)
library(mice)
library(naniar)
library(plotly) 
library(webshot)
library(zoo)

```

```{r}
rm(list=ls())
```

CREACION DE LAS RUTAS DE LOS FICHEROS.

```{r}
ruta1<- "data/1059xlxveei79_ECGf2/27_09_2022"
ruta2<-"data/0519xxxiii14/06_02_2023"
ruta3<- "data/0795xalvii8a7/27_09_2022"
ruta4<- "data/ecg5_210xlxi81_IP_39_eBR_BRP_720"

rutas<- c(ruta1,ruta2,ruta3,ruta4)
poner_horas <- function(x){
  horas <-list.dirs(x, recursive = FALSE)
  return(horas)
}
poner_ficheros <- function(x,y){
  ruta_analogica <- file.path(x[1], y[3])
  ruta_canalogica <- file.path(x[1], y[1])
  ruta_digital <-  file.path(x[1], y[4])
  ruta_cdigital <- file.path(x[1], y[2])
  return(c(ruta_analogica, ruta_canalogica, ruta_digital, ruta_cdigital))
}
horas <-c()
for (i in rutas){
  a <- poner_horas(i)
  horas<- c(horas,a)
}

ficheros <- list.files(horas[1])

rutas_completas <- c()
for (i in seq_along(horas)) {
  res <- poner_ficheros(horas[i], ficheros)
  rutas_completas <- c(rutas_completas, res)
}
rutas_completas <- head(rutas_completas,-4)

```

NUMERO DE LECTURAS QUE HABRÁ QUE HACER EN CADA FICHERO ANALOGICO:
```{r}
lecturas <- c()
for (i in seq(from = 1, to = length(rutas_completas), by = 4)) {
  info_fichero <- file.info(rutas_completas[i])
  tamanio_fichero <- info_fichero$size
  numero <- tamanio_fichero/2
  lecturas <- c(lecturas, numero)
}
  

```


NUMERO DE LECTURAS QUE HABRÁ QUE HACER EN CADA FICHERO DIGITAL:
```{r}
lecturas_d <- c()
for (i in seq(from = 3, to = length(rutas_completas), by = 4)) {
  info_fichero <- file.info(rutas_completas[i])
  numero <- info_fichero$size
  lecturas_d <- c(lecturas_d, numero)
}

```

LECTURAS DE LOS FICHEROS

```{r}
info_fichero <- file.info(rutas_completas[1])
tamanio_fichero <- info_fichero$size
numero <- tamanio_fichero/2

#FICHEROS ANALOGICOS
An1<- readBin(con = rutas_completas[1], signed=T, what= integer(), size=2,n=lecturas[1])
An2<- readBin(con = rutas_completas[5], signed=T, what= integer(), size=2,n=lecturas[2])
An3<- readBin(con = rutas_completas[9], signed=T, what= integer(), size=2,n=lecturas[3])
An4<- readBin(con = rutas_completas[13], signed=T, what= integer(), size=2,n=lecturas[4])
An5<- readBin(con = rutas_completas[17], signed=T, what= integer(), size=2,n=lecturas[5])
An6<- readBin(con = rutas_completas[21], signed=T, what= integer(), size=2,n=lecturas[6])
#CABECERAS FICHEROS ANALOGICOS PARTE 1/3
Can1 <- readBin(con = rutas_completas[2], signed=F, what= integer(), size=1, n=7)
Can2 <- readBin(con = rutas_completas[6], signed=F, what= integer(), size=1, n=7)
Can3 <- readBin(con = rutas_completas[10], signed=F, what= integer(), size=1, n=7)
Can4 <- readBin(con = rutas_completas[14], signed=F, what= integer(), size=1, n=7)
Can5 <- readBin(con = rutas_completas[18], signed=F, what= integer(), size=1, n=7)
Can6 <- readBin(con = rutas_completas[22], signed=F, what= integer(), size=1, n=7)
#CABECERAS FICHEROS ANALOGICOS PARTE 2/3
aux1 <- file(rutas_completas[2],'rb')
aux2 <- file(rutas_completas[6],'rb')
aux3 <- file(rutas_completas[10],'rb')
aux4 <- file(rutas_completas[14],'rb')
aux5 <- file(rutas_completas[18],'rb')
aux6 <- file(rutas_completas[22],'rb')
seek(aux1, 7)
seek(aux2, 7)
seek(aux3, 7)
seek(aux4, 7)
seek(aux5, 7)
seek(aux6, 7)

Can1_2 <- readBin(con = aux1, signed=T, what= integer(), size=2, n=3)
Can2_2 <- readBin(con = aux2, signed=T, what= integer(), size=2, n=3)
Can3_2 <- readBin(con = aux3, signed=T, what= integer(), size=2, n=3)
Can4_2 <- readBin(con = aux4, signed=T, what= integer(), size=2, n=3)
Can5_2 <- readBin(con = aux5, signed=T, what= integer(), size=2, n=3)
Can6_2 <- readBin(con = aux6, signed=T, what= integer(), size=2, n=3)
#CABECERAS FICHEROS ANALOGICOS PARTE 3/3

Can1 <- c(Can1,Can1_2)
Can2 <- c(Can2,Can2_2)
Can3 <- c(Can3,Can3_2)
Can4 <- c(Can4,Can4_2)
Can5 <- c(Can5,Can5_2)
Can6 <- c(Can6,Can6_2)

#FICHEROS DIGITALES
Dig1 <- readBin(con = rutas_completas[3], signed=F, what= integer(), size=1, n=lecturas_d[1])
Dig2 <- readBin(con = rutas_completas[7], signed=F, what= integer(), size=1, n=lecturas_d[2])
Dig3 <- readBin(con = rutas_completas[11], signed=F, what= integer(), size=1, n=lecturas_d[3])
Dig4 <- readBin(con = rutas_completas[15], signed=F, what= integer(), size=1, n=lecturas_d[4])
Dig5 <- readBin(con = rutas_completas[19], signed=F, what= integer(), size=1, n=lecturas_d[5])
Dig6 <- readBin(con = rutas_completas[23], signed=F, what= integer(), size=1, n=lecturas_d[6])

#CABECERAS FICHEROS DIGITALES
Cdig1 <- readBin(con = rutas_completas[4], signed=F, what= integer(), size=1, n=8)
Cdig2 <- readBin(con = rutas_completas[8], signed=F, what= integer(), size=1, n=8)
Cdig3 <- readBin(con = rutas_completas[12], signed=F, what= integer(), size=1, n=8)
Cdig4 <- readBin(con = rutas_completas[16], signed=F, what= integer(), size=1, n=8)
Cdig5 <- readBin(con = rutas_completas[20], signed=F, what= integer(), size=1, n=8)
Cdig6 <- readBin(con = rutas_completas[24], signed=F, what= integer(), size=1, n=8)

``` 
CREACIÓN DE LOS DATA FRAME CON LA INFORMACIÓN DEL FICHERO DIGITAL.
```{r}
crear_df_digital <- function(x){
  HR1 <- x[seq(from = 1, to = length(x), by = 9)]
  HR2 <- x[seq(from = 2, to = length(x), by = 9)]
  MHR <- x[seq(from = 3, to = length(x), by = 9)]
  TOCO <- x[seq(from = 4, to = length(x), by = 9)]
  SPO2 <- x[seq(from = 5, to = length(x), by = 9)]
  VCP <- x[seq(from = 6, to = length(x), by = 9)]
  PSI <- x[seq(from = 7, to = length(x), by = 9)]
  PDI <- x[seq(from = 8, to = length(x), by = 9)]
  PME <- x[seq(from = 9, to = length(x), by = 9)]
  df <- data.frame(HR1,HR2,MHR,TOCO,SPO2,VCP,PSI,PDI,PME)
  return(df)
}

Dig1<-crear_df_digital(Dig1)
Dig2<-crear_df_digital(Dig2)
Dig3<-crear_df_digital(Dig3)
Dig4<-crear_df_digital(Dig4)
Dig5<-crear_df_digital(Dig5)
Dig6<-crear_df_digital(Dig6)


```

GRAFICA DEL EJEMPLO
```{r}
library(ggplot2)
library(plotly)

ult_An <- tail(An1, n = 10000)
t <- 1:length(An1)
ult_t <- tail(t/1000, n = 10000)

p <- ggplot(data = data.frame(x = ult_t, y = ult_An), aes(x = x, y = y)) + 
  geom_line(color = "blue", size =0.5) +
  labs(x = "Tiempo(s)", y = "Frecuencia(Hz)") +
  ylim(-300, 1000) +
  theme_gray() +
  theme(panel.grid.major = element_line(linetype = "dashed", color = "gray", size = 1))

ggplotly(p)

ult_An <- tail(An1, n = 10000)
t <- 1:length(An1)
ult_t <- tail(t/1000, n = 10000)
plot(ult_t, ult_An, ylim = c(-300,1000), xlab = "Tiempo(s)", ylab = "Frecuencia(Hz)",type = "l", col = "blue", lwd = 2)
grid(nx = NULL, ny = NULL,
    lty = 2, col = "gray", lwd = 1)
abline(h = 
         , col = "black", lty = 2)



ggplotly(p)

#Gráfica interactiva

``` 

```{r}
Data_frame_largo <- function(x){
  L <- x%>%
    pivot_longer(cols= HR1:PME, names_to = "variable")
  L <- L%>%
      mutate(time = seq(1/9, nrow(L)/9, by= 1/9))
  return(L)
}

Dig1_L <- Data_frame_largo(Dig1)
Dig2_L <- Data_frame_largo(Dig2)
Dig3_L <- Data_frame_largo(Dig3)
Dig4_L <- Data_frame_largo(Dig4)
Dig5_L <- Data_frame_largo(Dig5)
Dig6_L <- Data_frame_largo(Dig6)  

         
ggplot(Dig1_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y") 
ggplot(Dig2_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y") 
``` 

GRAFICAS DE CADA FICHERO DIGITAL 
```{r}
ggplot(Dig1_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y") 
ggplot(Dig2_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y") 
#PODEMOS OBSERVAR QUE NO HAY VALORES DE HR2 PARA EL SEGUNDO FICHERO DIGITAL

ggplot(Dig3_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y")
#EL TERCER FICHERO DIGITAL SOLO TIENE INFORMACIÓN DE HR1 Y TOCO

ggplot(Dig4_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y")
#EL CUARTO FICHERO DIGITAL SOLO TIENE INFORMACIÓN DE HR1, TOCO Y VCP
ggplot(Dig5_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y")
#EL QUINTO FICHERO DIGITAL NO TIENE INFORMACIÓN DE PDI, PME Y PSI

ggplot(Dig6_L, aes(x = time, y = value)) + 
  geom_line()+ 
  facet_wrap(~ variable, scales = "free_y")
#EL SEXTO FICHERO DIGITAL NO TIENE INFORMACIÓN DE PDI, PME, PSI Y SPO2

```


```{r}
sum(is.na(An1))
sum(is.na(An2))
sum(is.na(An3))
sum(is.na(An4))
sum(is.na(An5))
sum(is.na(An6))


gg_miss_var(Dig1)
gg_miss_var(Dig2)
gg_miss_var(Dig3)
gg_miss_var(Dig4)
gg_miss_var(Dig5)
gg_miss_var(Dig6)

#NO HAY VALORES FALTANTES EN NINGÚN FICHERO DIGITAL NI ANALÓGICO.


```



COMPROBACIÓN DE OUTLIERS
```{r}
reglaboxplot <- function(x) {
  xs <- quantile(x, probs = 0.75,na.rm=T)
  xi <- quantile(x, probs = 0.25,na.rm=T)
  IQR <- xs - xi
  up <- xs + 1.5 * IQR
  low <- xi - 1.5 * IQR
  outliers <- x < low | x > up
  return(outliers)
}

#SUSTITUCIÓN DE LOS OUTLIERS EN HR1 POR LA REGLA DEL VECINO MÁS PROXIMO
outliers1 <- reglaboxplot(Dig1$HR1)
outliers2 <- reglaboxplot(Dig2$HR1)
outliers3 <- reglaboxplot(Dig3$HR1)
outliers4 <- reglaboxplot(Dig4$HR1)
outliers5 <- reglaboxplot(Dig5$HR1)
outliers6 <- reglaboxplot(Dig6$HR1)

Dig1$HR1[outliers1] <- NA
Dig1$HR1 <- na.locf(Dig1$HR1)
Dig2$HR1[outliers2] <- NA
Dig2$HR1 <- na.locf(Dig2$HR1)
Dig3$HR1[outliers3] <- NA
Dig3$HR1 <- na.locf(Dig3$HR1)
Dig4$HR1[outliers4] <- NA
Dig4$HR1 <- na.locf(Dig4$HR1)
Dig5$HR1[outliers5] <- NA
Dig5$HR1 <- na.locf(Dig5$HR1)
Dig6$HR1[outliers6] <- NA
Dig6$HR1 <- na.locf(Dig6$HR1)



Anadir_tiempo<- function(x){
  Time <- c(1:nrow(x))
  x <- cbind(x,Time)
  return(x)
}
Dig1 <- Anadir_tiempo(Dig1)
Dig2 <- Anadir_tiempo(Dig2)
Dig3 <- Anadir_tiempo(Dig3)
Dig4 <- Anadir_tiempo(Dig4)
Dig5 <- Anadir_tiempo(Dig5)
Dig6 <- Anadir_tiempo(Dig6)


ggplot(Dig1, aes(x=Time, y= HR1))+
  geom_line()
ggplot(Dig2, aes(x=Time, y= HR1))+
  geom_line()
ggplot(Dig3, aes(x=Time, y= HR1))+
  geom_line()
ggplot(Dig4, aes(x=Time, y= HR1))+
  geom_line()
ggplot(Dig5, aes(x=Time, y= HR1))+
  geom_line()
ggplot(Dig6, aes(x=Time, y= HR1))+
  geom_line()

```

